
#' plot_funct_markers
#'
#' Plot the expression of functional markers in all patients' cells, per
#' metacluster. This information can be generated with the
#' extract_funct_markers() function.
#'
#' @param metaclust_values list of matrices containing the cell expression of
#' the functional markers for all patients, per metacluster, as generated by the
#' function extract_funct_markers
#' @param patient_names list of the patient names, same as was passed to the
#' extract_funt_markers function
#'
#' @return a list of MFIs matrices for each column to use
#' @export
#'
#' @examples
#' funct_matrices <- extract_funct_markers(recip_names, fsom, fcs_dir, cols_to_use,
#'                                         min_ref, max_ref, files2rescale = c("D1073"))
#'
plot_funct_markers <- function(metaclust_values, patient_names, samp_patients){



  pdf("~/Desktop/test.pdf")
  #for (metacluster in seq_along(metaclust_values)){
    #for (marker in 1:(ncol(metaclust_values[[metacluster]])-1)){ RESTORE THE LOOP ONCE IVE TALKED TO ROBRECHT !
      ggplot(metaclust_values[[metacluster]]) +
        #geom_point(aes(x = patients,#colnames(metaclust_values[[metacluster]])[marker],
        #               y = Cd114Di)) +
        geom_jitter(aes(x = patients, y = Cd114Di, col = as.factor(batch)),
                    height = 0, width = 0.3, size = 0.7)
    ggplot(metaclust_values[[metacluster]]) +
      geom_jitter(aes(x = patients, y = Nd150Di, col = as.factor(batch)),
                  height = 0, width = 0.3, size = 0.7)
    ggplot(metaclust_values[[metacluster]]) +
      geom_jitter(aes(x = patients, y = Eu151Di, col = as.factor(batch)),
                  height = 0, width = 0.3, size = 0.7)
    ggplot(metaclust_values[[metacluster]]) +
      geom_jitter(aes(x = patients, y = Sm154Di, col = as.factor(batch)),
                  height = 0, width = 0.3, size = 0.7)
    ggplot(metaclust_values[[metacluster]]) +
      geom_jitter(aes(x = patients, y = Gd158Di, col = as.factor(batch)),
                  height = 0, width = 0.3, size = 0.7)
    ggplot(metaclust_values[[metacluster]]) +
      geom_jitter(aes(x = patients, y = Dy161Di, col = as.factor(batch)),
                  height = 0, width = 0.3, size = 0.7)
    ggplot(metaclust_values[[metacluster]]) +
      geom_jitter(aes(x = patients, y = Yb171Di, col = as.factor(batch)),
                  height = 0, width = 0.3, size = 0.7)


    ggplot(metaclust_values[[metacluster]]) +
      #geom_point(aes(x = patients,#colnames(metaclust_values[[metacluster]])[marker],
      #               y = Cd114Di)) +
      geom_jitter(aes(x = patients, y = Cd114Di, col = as.factor(group)),
                  height = 0, width = 0.3, size = 0.7)
    ggplot(metaclust_values[[metacluster]]) +
      geom_jitter(aes(x = patients, y = Nd150Di, col = as.factor(group)),
                  height = 0, width = 0.3, size = 0.7)
    ggplot(metaclust_values[[metacluster]]) +
      geom_jitter(aes(x = patients, y = Eu151Di, col = as.factor(group)),
                  height = 0, width = 0.3, size = 0.7)
    ggplot(metaclust_values[[metacluster]]) +
      geom_jitter(aes(x = patients, y = Sm154Di, col = as.factor(group)),
                  height = 0, width = 0.3, size = 0.7)
    ggplot(metaclust_values[[metacluster]]) +
      geom_jitter(aes(x = patients, y = Gd158Di, col = as.factor(group)),
                  height = 0, width = 0.3, size = 0.7)
    ggplot(metaclust_values[[metacluster]]) +
      geom_jitter(aes(x = patients, y = Dy161Di, col = as.factor(group)),
                  height = 0, width = 0.3, size = 0.7)
    ggplot(metaclust_values[[metacluster]]) +
      geom_jitter(aes(x = patients, y = Yb171Di, col = as.factor(group)),
                  height = 0, width = 0.3, size = 0.7)
    dev.off()

    #}
  #}

}

